### ISSUE TITLE
As a Proxima user, I want to have the ability to delete my posts even if I'm not currently near their locations, to have complete control over my online image.

### ISSUE THREAD

**Issue by TheTexanCodeur** [ProximaEPFL/proxima#12]
Acceptance criteria:
- Post made by a user can be deleted from profile page
- On deletion, the post disappears from both the profile page and the feed.
- On deletion, the post disappears from other users feed.

**Comment by camillelnne** [comment]
User stories:
- As a user, I want to delete my post in case I change my opinion
- As a user, I want to access to delete my posts from anywhere.
- As a user, I want my deleted posts to disappear from others views

Done on completion of:
- #103 
- #170 
- #205 
- #206
