### ISSUE TITLE
As a Proxima user, I want to see a map with the position of the posts of my feed, so that I can know exactly where they were posted

### ISSUE THREAD

**Issue by JoachimFavre** [ProximaEPFL/proxima#136]
Acceptance criteria:
- There must be a map on the map page
- The user position should be displayed even when they move
- A circle of radius 100m should be displayed around the user position
- All the posts currently in the feed should have a pin corresponding to where they were posted

**Comment by CHOOSEIT** [comment]
User stories:
- #241
