### ISSUE TITLE
Add timeout on circular values for offline mode

### ISSUE THREAD

**Issue by CHOOSEIT** [ProximaEPFL/proxima#278]
Acceptance criterias:
- [ ] Have a timeout on the circular value
- [ ] Display a snackbar message on reaching timeout
- [ ] Have a retry button instead of spinning forever
- [ ] Adapt main circular value uses to have the new timeout

**Comment by gruvw** [comment]
- have a timeout on the circular value
- display a snackbar message on reaching timeout
- have a retry button instead of spinning forever
- adapt main circular value uses to have the new timeout
