### ISSUE TITLE
Ranking view model

### ISSUE THREAD

**Issue by CHOOSEIT** [ProximaEPFL/proxima#299]
Acceptance criterias:
- [x] Retrieve users that have most points from DB
- [x] Create new UI model class to expose user ranking fields
- [x] Write a viewmodel with public API to get the top 50 users of the app
- [x] Write another function to get the current user (potentially with its own UI model class)

**Comment by gruvw** [comment]
- Retrieve users that have most points from DB
- Create new UI model class to expose user leaderboard fields
- Write a viewmodel with public API to get the top 50 users of the app
- Write another function to get the current user (potentially with its own UI model class)
