### ISSUE TITLE
Create mockup for new post page

### ISSUE THREAD

**Issue by Aderfish** [ProximaEPFL/proxima#61]

**Comment by gruvw** [comment]
![image](https://github.com/ProximaEPFL/proxima/assets/63407038/f797ba15-a692-47a2-8cd4-e786d17a8214)
Done

Linking with overview page
![image](https://github.com/ProximaEPFL/proxima/assets/63407038/aaa2d4c2-7872-4050-bb6f-98017ffbb8ae)
