### ISSUE TITLE
As a user, I want to be able to comment on a post, so that I can share my thoughts about it.

### ISSUE THREAD

**Issue by Aderfish** [ProximaEPFL/proxima#91]
Acceptance criteria:
- The text field at the bottom of the view post page should work and write a comment to the repository on "send"
- Comments should be displayed on the post page

**Comment by camillelnne** [comment]
Done on completion of the following tasks/user stories:

- [x] #176 
- [x] #138
- [ ] #212
- [ ] #224

**Comment by camillelnne** [comment]
Closed on completion of the referenced tasks.
